// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.6
// source: sampling/sampling_grpc/sampling.proto

package sampling_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type View struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Descriptors []*Descriptor `protobuf:"bytes,1,rep,name=Descriptors,proto3" json:"Descriptors,omitempty"`
	C           int32         `protobuf:"varint,2,opt,name=C,proto3" json:"C,omitempty"`
	SourceIp    string        `protobuf:"bytes,3,opt,name=SourceIp,proto3" json:"SourceIp,omitempty"`
	SourcePort  int32         `protobuf:"varint,4,opt,name=SourcePort,proto3" json:"SourcePort,omitempty"`
}

func (x *View) Reset() {
	*x = View{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sampling_sampling_grpc_sampling_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *View) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*View) ProtoMessage() {}

func (x *View) ProtoReflect() protoreflect.Message {
	mi := &file_sampling_sampling_grpc_sampling_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use View.ProtoReflect.Descriptor instead.
func (*View) Descriptor() ([]byte, []int) {
	return file_sampling_sampling_grpc_sampling_proto_rawDescGZIP(), []int{0}
}

func (x *View) GetDescriptors() []*Descriptor {
	if x != nil {
		return x.Descriptors
	}
	return nil
}

func (x *View) GetC() int32 {
	if x != nil {
		return x.C
	}
	return 0
}

func (x *View) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *View) GetSourcePort() int32 {
	if x != nil {
		return x.SourcePort
	}
	return 0
}

type Descriptor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip   string `protobuf:"bytes,1,opt,name=Ip,proto3" json:"Ip,omitempty"`
	Port int32  `protobuf:"varint,2,opt,name=Port,proto3" json:"Port,omitempty"`
	Age  int64  `protobuf:"varint,3,opt,name=Age,proto3" json:"Age,omitempty"`
}

func (x *Descriptor) Reset() {
	*x = Descriptor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sampling_sampling_grpc_sampling_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Descriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Descriptor) ProtoMessage() {}

func (x *Descriptor) ProtoReflect() protoreflect.Message {
	mi := &file_sampling_sampling_grpc_sampling_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Descriptor.ProtoReflect.Descriptor instead.
func (*Descriptor) Descriptor() ([]byte, []int) {
	return file_sampling_sampling_grpc_sampling_proto_rawDescGZIP(), []int{1}
}

func (x *Descriptor) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Descriptor) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Descriptor) GetAge() int64 {
	if x != nil {
		return x.Age
	}
	return 0
}

var File_sampling_sampling_grpc_sampling_proto protoreflect.FileDescriptor

var file_sampling_sampling_grpc_sampling_proto_rawDesc = []byte{
	0x0a, 0x25, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e, 0x67, 0x2f, 0x73, 0x61, 0x6d, 0x70, 0x6c,
	0x69, 0x6e, 0x67, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7f, 0x0a, 0x04, 0x56, 0x69, 0x65, 0x77, 0x12,
	0x2d, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f,
	0x72, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x0c,
	0x0a, 0x01, 0x43, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x43, 0x12, 0x1a, 0x0a, 0x08,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x53, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x22, 0x42, 0x0a, 0x0a, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x49, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x67,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x41, 0x67, 0x65, 0x32, 0x24, 0x0a, 0x08,
	0x53, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x08, 0x45, 0x78, 0x63, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x12, 0x05, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x1a, 0x05, 0x2e, 0x56, 0x69,
	0x65, 0x77, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e, 0x67,
	0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sampling_sampling_grpc_sampling_proto_rawDescOnce sync.Once
	file_sampling_sampling_grpc_sampling_proto_rawDescData = file_sampling_sampling_grpc_sampling_proto_rawDesc
)

func file_sampling_sampling_grpc_sampling_proto_rawDescGZIP() []byte {
	file_sampling_sampling_grpc_sampling_proto_rawDescOnce.Do(func() {
		file_sampling_sampling_grpc_sampling_proto_rawDescData = protoimpl.X.CompressGZIP(file_sampling_sampling_grpc_sampling_proto_rawDescData)
	})
	return file_sampling_sampling_grpc_sampling_proto_rawDescData
}

var file_sampling_sampling_grpc_sampling_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sampling_sampling_grpc_sampling_proto_goTypes = []interface{}{
	(*View)(nil),       // 0: View
	(*Descriptor)(nil), // 1: Descriptor
}
var file_sampling_sampling_grpc_sampling_proto_depIdxs = []int32{
	1, // 0: View.Descriptors:type_name -> Descriptor
	0, // 1: Sampling.Exchange:input_type -> View
	0, // 2: Sampling.Exchange:output_type -> View
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sampling_sampling_grpc_sampling_proto_init() }
func file_sampling_sampling_grpc_sampling_proto_init() {
	if File_sampling_sampling_grpc_sampling_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sampling_sampling_grpc_sampling_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*View); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sampling_sampling_grpc_sampling_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Descriptor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sampling_sampling_grpc_sampling_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sampling_sampling_grpc_sampling_proto_goTypes,
		DependencyIndexes: file_sampling_sampling_grpc_sampling_proto_depIdxs,
		MessageInfos:      file_sampling_sampling_grpc_sampling_proto_msgTypes,
	}.Build()
	File_sampling_sampling_grpc_sampling_proto = out.File
	file_sampling_sampling_grpc_sampling_proto_rawDesc = nil
	file_sampling_sampling_grpc_sampling_proto_goTypes = nil
	file_sampling_sampling_grpc_sampling_proto_depIdxs = nil
}
