// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.6
// source: vivaldi/vivaldi_grpc/vivaldi.proto

package vivaldi_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VivaldiClient is the client API for Vivaldi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VivaldiClient interface {
	GetCoord(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Coord, error)
}

type vivaldiClient struct {
	cc grpc.ClientConnInterface
}

func NewVivaldiClient(cc grpc.ClientConnInterface) VivaldiClient {
	return &vivaldiClient{cc}
}

func (c *vivaldiClient) GetCoord(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Coord, error) {
	out := new(Coord)
	err := c.cc.Invoke(ctx, "/Vivaldi/GetCoord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VivaldiServer is the server API for Vivaldi service.
// All implementations must embed UnimplementedVivaldiServer
// for forward compatibility
type VivaldiServer interface {
	GetCoord(context.Context, *emptypb.Empty) (*Coord, error)
	mustEmbedUnimplementedVivaldiServer()
}

// UnimplementedVivaldiServer must be embedded to have forward compatible implementations.
type UnimplementedVivaldiServer struct {
}

func (UnimplementedVivaldiServer) GetCoord(context.Context, *emptypb.Empty) (*Coord, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCoord not implemented")
}
func (UnimplementedVivaldiServer) mustEmbedUnimplementedVivaldiServer() {}

// UnsafeVivaldiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VivaldiServer will
// result in compilation errors.
type UnsafeVivaldiServer interface {
	mustEmbedUnimplementedVivaldiServer()
}

func RegisterVivaldiServer(s grpc.ServiceRegistrar, srv VivaldiServer) {
	s.RegisterService(&Vivaldi_ServiceDesc, srv)
}

func _Vivaldi_GetCoord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VivaldiServer).GetCoord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Vivaldi/GetCoord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VivaldiServer).GetCoord(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Vivaldi_ServiceDesc is the grpc.ServiceDesc for Vivaldi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Vivaldi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Vivaldi",
	HandlerType: (*VivaldiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCoord",
			Handler:    _Vivaldi_GetCoord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vivaldi/vivaldi_grpc/vivaldi.proto",
}
